version: "3"
networks:
  expense:
volumes:
  mysql:
services:
  mysql:
    image: lakshman045/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
    
  backend:
     image: lakshman045/backend:v1
     container_name: backend
     command: sh -c "sleep 10 && node /opt/server/index.js"
     depends_on:
     - mysql
  frontend:
     image: lakshman045/frontend:v1
     container_name: frontend
     ports:
     - 80:80
     depends_on:
     - backend

     
